services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      TZ: Asia/Shanghai
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 10002
  server:
    image: ghcr.io/sdmht/sdmht-server:main
    restart: always
    ports:
      - target: 8000
        published: 10003
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: release
      GORM_DSN: host=db user=postgres password=${POSTGRES_PASSWORD} dbname=postgres port=5432 sslmode=disable
    depends_on:
      - db
